Reorganize steps in build workflow for improved readability

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -28,31 +28,31 @@ jobs:
       with:
         python-version: ${{ matrix.python-version }}
 
-      - name: Install dependencies
-        # install all requirements. Note that the full requirements are installed separately
-        # so the job does not fail if one of the packages cannot be installed. This allows
-        # testing the package for newer python version even when some of the optional
-        # packages are not yet available.
-        run: |
-          python -m pip install --upgrade pip
-          pip install -r requirements.txt
-          cat tests/requirements_full.txt | sed -e '/^\s*#.*$/d' -e '/^\s*$/d' | xargs -I % sh -c "pip install % || true"
-          pip install -r tests/requirements.txt
+    - name: Install dependencies
+      # install all requirements. Note that the full requirements are installed separately
+      # so the job does not fail if one of the packages cannot be installed. This allows
+      # testing the package for newer python version even when some of the optional
+      # packages are not yet available.
+      run: |
+        python -m pip install --upgrade pip
+        pip install -r requirements.txt
+        cat tests/requirements_full.txt | sed -e '/^\s*#.*$/d' -e '/^\s*$/d' | xargs -I % sh -c "pip install % || true"
+        pip install -r tests/requirements.txt
 
-      - name: Include submodules in python path
-        run: |
-          echo "PYTHONPATH=$PWD/submodules/py-droplets:$PWD/submodules/py-modelrunner:$PWD/submodules/py-pde:$PYTHONPATH" >> $GITHUB_ENV
+    - name: Include submodules in python path
+      run: |
+        echo "PYTHONPATH=$PWD/submodules/py-droplets:$PWD/submodules/py-modelrunner:$PWD/submodules/py-pde:$PYTHONPATH" >> $GITHUB_ENV
 
-      - name: Test with pytest
-        env:
-          NUMBA_WARNINGS: 1
-          MPLBACKEND: agg
-        run: |
-          pip install pytest
-          cd scripts
-          python run_tests.py --unit --parallel
+    - name: Test with pytest
+      env:
+        NUMBA_WARNINGS: 1
+        MPLBACKEND: agg
+      run: |
+        pip install pytest
+        cd scripts
+        python run_tests.py --unit --parallel
 
-      - name: Test types with mypy
-        continue-on-error: true
-        run: |
-          python -m mypy --config-file pyproject.toml --pretty --package sim
+    - name: Test types with mypy
+      continue-on-error: true
+      run: |
+        python -m mypy --config-file pyproject.toml --pretty --package sim
